### ISSUE TITLE
Step 3

### ISSUE THREAD

**Issue by dovian123** [ThunderGemios10/The-Super-Duper-Script-Editor-2#3]
The OK and Skip on step 3 does not work, alsowill you please teach me how to install it? I sent something to your gmail... please reply please...

**Comment by ThunderGemios10** [comment]
That's odd, The skip and OK buttons on Step 3 worked when i added it.
I'll try to debug the problem.

One question:
Are you trying to edit the scripts of the PSP version or PC version?

**Comment by ThunderGemios10** [comment]
UPDATE: I have fixed the skip button. Please download a new copy of the script editor.

**Comment by dovian123** [comment]
Um... I'm trying to translate it using the orenronen translation... but I'm looking forward for your translation...
Question... Will you stop this project at some point? cause I'm really...really looking forward for this...

**Comment by dovian123** [comment]
Also, the "OK" button works but does not proceed to Step 4, so I have no choice to press Skip...
And when you set up the work space... for some reason it's stuck at 83%...
Sorry for bothering you...
but...Will you stop this project at some point? cause I'm really...really looking forward for this...

**Comment by ThunderGemios10** [comment]
@dovian123 If you have seen my latest commit, No, I am continuing the project. Also what do you mean it gets stuck at %83? Which Step? What does it say?

**Comment by ThunderGemios10** [comment]
@dovian123 Also, Which versions are you translating? PSP or the PC/Steam version?

**Comment by ThunderGemios10** [comment]
@dovian123 I just realized you are trying to translate the PSP version into English. Please do not.. There is already a english version for PC/Steam.

**Comment by dovian123** [comment]
**Step 4**, when setting up the work space it's stuck at 83% i **think** it says **copying editor data**...?
And in **Step 5**, It's stuck at 0%...
I know... I even manage to defeat the 2 games on PC... but I want to use it so bad...
I'm really **really** sorry for bothering... but will you make a tutorial soon?

**Comment by dovian123** [comment]
Hey dude... how's the project going?

**Comment by dovian123** [comment]
How bout the tutorial?

**Comment by ThunderGemios10** [comment]
@dovian123 I am working on it.

**Comment by dovian123** [comment]
Im really sorry for bothering...

**Comment by dovian123** [comment]
@ThunderGemios10 Are you working on the tutorial or the game?

**Comment by ThunderGemios10** [comment]
@dovian123 I can't work on a tutorial since i'm very busy :(, But rest assured! A tutorial will come in the near future!
