### ISSUE TITLE
"GFX"?

### ISSUE THREAD

**Issue by ProfessorTrickRoom** [ThunderGemios10/The-Super-Duper-Script-Editor-2#4]
I have one small question: What are you exactly implying by "the GFX" that is required for this editor to work?

**Comment by ThunderGemios10** [comment]
You need "dr2_editor_gfx.rar" for the Editor to work.

Download it at "Releases" and place it on /data/ folder.

**Comment by ProfessorTrickRoom** [comment]
Thanks so very much!
