### ISSUE TITLE
Where is data/editor_data.zip?

### ISSUE THREAD

**Issue by nnn1590** [ThunderGemios10/The-Super-Duper-Script-Editor-2#5]
Where is data/editor_data.zip?
data/editor_data.zipはどこですか？
___
![Step 4 Extracting editor data...](https://user-images.githubusercontent.com/28985763/59930003-e62bda80-947c-11e9-8440-035f03294f12.png)

**ドキュメント** = **Documents**
**そのようなファイルやディレクトリはありません** = **No such file or directory**
`~/ドキュメント/The-Super-Duper-Script-Editor-2$ python editor.pyw`
> Traceback (most recent call last):
>   File "/home/nnn1590/ドキュメント/The-Super-Duper-Script-Editor-2/setup_wizard.py", line 330, in setup_workspace
>     editor_data = zipfile.ZipFile("data/editor_data.zip", "r")
>   File "/usr/lib/python2.7/zipfile.py", line 779, in \_\_init\_\_
>     self.fp = open(file, modeDict[mode])
> IOError: [Errno 2] そのようなファイルやディレクトリはありません: 'data/editor_data.zip'
___
I downloaded rar from Release and expanded it to `data/gfx`.
But `editor_data.zip` is not found anywhere.
Where is `editor_data.zip`?

`data/file_order.txt` has been changed to the GNU/Linux path.
For example, from `\PSP_GAME\SYSDIR\EBOOT.BIN` to `\PSP_GAME/SYSDIR/EBOOT.BIN`.
It is because it fails in Step 1 if do not change it.

Also, `extract/cpk_uncompress.dll` has been changed to GNU/Linux binary by executing `make` from `extract/cpk`.
The file name remains `cpk_uncompress.dll`.

This document was translated from Japanese to English by Google Translate.
___
私はReleaseからrarをダウンロードし`data/gfx`に展開しました。
しかし`editor_data.zip`はどこにも見つかりません。
`editor_data.zip`はどこですか？

`data/file_order.txt`はGNU/Linux向けのパスに変更しました。
例えば`\PSP_GAME\SYSDIR\EBOOT.BIN`から`\PSP_GAME/SYSDIR/EBOOT.BIN`に。
変更しないとStep 1で失敗するからです。

また、`extract/cpk`で`make`を実行して`extract/cpk_uncompress.dll`をGNU/Linux向けのバイナリに変更しました。
ファイル名は`cpk_uncompress.dll`のままです。

この文書はGoogle翻訳によって日本語から英語に翻訳されました。
___
OS: Ubuntu GNU/Linux 18.04 LTS (amd64, Japanese-remix)
Python: 2.7.15+

**Comment by ThunderGemios10** [comment]
https://github.com/ThunderGemios10/The-Super-Duper-Script-Editor-2/releases

**Comment by nnn1590** [comment]
Thank you!

**Comment by nnn1590** [comment]
`zip -r editor_data.zip The-Super-Duper-Script-Editor-2`
